version: "3.8"

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins-data:
  jenkins-docker-certs:

services:
  jenkins_master:
    build:
      context: .
      #ARGS used for Building docker image, ENV is used within container
      args:
        - DOCKER_HOST_IP=${DOCKER_HOST_IP}
    networks:
      - jenkins
    container_name: jenkins-master
    restart: always
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - JENKINS_USERNAME=${JENKINS_USERNAME}
      - JENKINS_PASSWORD=${JENKINS_PASSWORD}
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home:rw
      - jenkins-docker-certs:/certs/client:ro
      - /var/run/docker.sock:/var/run/docker.sock

  docker_in_docker:
    image: docker:dind
    networks:
      jenkins:
        aliases:
          - docker
    container_name: docker-in-docker
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    ports:
      - "2376:2376"
      - "2375:2375"
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
